spring:
    h2:
        console:
            enabled: true
            path: /h2-console
    datasource:
        url: jdbc:h2:mem:demo_bank;MODE=MySQL;DATABASE_TO_LOWER=TRUE
        username: sa
        password: